shell = "bash -c '{}'"

[[items]]
file="~/.Xresources"
template="xresources"
hook="xrdb ~/.Xresources"
start="! Start flavours"
end="! End flavours"

[[items]]
file="~/.config/alacritty/alacritty.yml"
template="alacritty"
hook="alacritty reset"

[[items]]
file = "~/.config/beautifuldiscord/style.css"
template = "styles"
subtemplate = "css-variables"
start= "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.config/spicetify/Themes/base16/color.ini"
template = "spotify"
rewrite = true

[[items]]
file="~/.config/i3/config"
template="i3"
subtemplate="client-properties"
hook="i3-msg restart"
